name: minerva_controller_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  minerva_controller:
    path: D:/Projects/Dart/generate_code_test/minerva_controller
  minerva_controller_annotation:
    path: D:/Projects/Dart/generate_code_test/minerva_controller_annotation
  source_gen: ^1.2.6
  build: ^2.3.1
  analyzer: ^5.3.1
  minerva:
    path: D:\GitHub\minerva

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
